trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest' 

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.2'
- script: |
    python -m pip install --upgrade pip
    pip install robotframework  # Install Robot Framework
  displayName: 'Install Robot Framework'

- script: |
    robot --output output.xml tests/  # Run Robot Framework tests
  displayName: 'Run Robot Framework Tests'

- script: |
    echo "Running tests..."
    robot --output output.xml tests/
  displayName: 'Run Robot Framework Tests'
  continueOnError: true  # This will allow the pipeline to continue and provide more logs

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Robot'
    testResultsFiles: '**/output.xml'
    mergeTestResults: true
  displayName: 'Publish Test Results'
