trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest'  # Or your preferred VM image

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.2'

- script: |
    echo "Listing files in the working directory"
    dir D:\a\1\s  # List the files in the working directory to verify the path
  displayName: 'List Files in Working Directory'

- script: |
    echo "Listing contents of the tests directory"
    dir D:\a\1\s\tests  # List the contents of the tests directory to verify it's correct
  displayName: 'List Contents of Tests Directory'

- script: |
    echo "Installing Robot Framework..."
    pip install robotframework
  displayName: 'Install Robot Framework'

- script: |
    echo "Running Robot Framework Tests..."
    robot --output output.xml D:\a\1\s\tests/  # Ensure the path is correct
  displayName: 'Run Robot Framework Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Robot'
    testResultsFiles: '**/output.xml'
    mergeTestResults: true
  displayName: 'Publish Test Results'
