trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest'

variables:
  ROBOT_REPORTS_DIR: 'robot_results'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.2'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
  displayName: 'Install Robot Framework and dependencies'
