trigger: none  # Don't trigger on code changes

resources:
  pipelines:
    - pipeline: AutomatedTestingPipeline
      source: AutomatedTesting-.NET Desktop-CI
      trigger: true  # Trigger when the source pipeline completes

variables:
  ROBOT_REPORTS_DIR: 'robot_results'

pool:
  vmImage: 'windows-latest'

steps:

# 1. Use Python 3.11
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

# 2. Install Edge WebDriver manually
- powershell: |
    $edgeVersion = (Get-Item "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe").VersionInfo.ProductVersion
    Write-Host "Detected Edge version: $edgeVersion"
    $url = "https://msedgedriver.azureedge.net/$edgeVersion/edgedriver_win64.zip"
    Write-Host "Downloading WebDriver from $url"
    Invoke-WebRequest -Uri $url -OutFile "edgedriver.zip"
    Expand-Archive -Path "edgedriver.zip" -DestinationPath "$(Build.SourcesDirectory)\edgedriver" -Force
    $env:PATH += ";$(Build.SourcesDirectory)\edgedriver"
  displayName: 'Install Edge WebDriver manually'

# 3. Install Robot Framework and dependencies
- script: |
    python -m pip install --upgrade pip || exit 1
    pip install robotframework==6.1.1 || exit 1
    pip install robotframework-seleniumlibrary==6.1.2 || exit 1
  displayName: 'Install Robot Framework and dependencies'

# 4. Run Robot Framework tests
- script: |
    robot --variable BROWSER:edge ^
          --output "$(ROBOT_REPORTS_DIR)\output.xml" ^
          --log "$(ROBOT_REPORTS_DIR)\log.html" ^
          --report "$(ROBOT_REPORTS_DIR)\report.html" ^
          robot_test/
  displayName: 'Run Robot Framework Tests'
  continueOnError: true  # Continue even if tests fail

# 5. Convert Robot Output to JUnit
- script: |
    rebot --xunit "$(ROBOT_REPORTS_DIR)\xunit.xml" "$(ROBOT_REPORTS_DIR)\output.xml"
  displayName: 'Convert Robot Output to JUnit'
  condition: always()

# 6. Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(ROBOT_REPORTS_DIR)\xunit.xml'
    testRunTitle: 'Robot Framework Test Results'
  condition: always()

# 7. Publish all Robot output files as artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(ROBOT_REPORTS_DIR)'
    artifactName: 'RobotResults'
  condition: always()

# 8. Rollback if regression tests fail
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'AutomatedTesting'  # Replace with your project name
    pipeline: 'AutomatedTesting-.NET Desktop-CI'  # The name of your system pipeline
    buildVersionToDownload: 'latestFromBranch'  # Get the latest successful build
    branchName: 'refs/heads/main'  # Replace with your branch name
    artifactName: 'drop'  # Artifact name
    targetPath: '$(Build.ArtifactStagingDirectory)/rollback'  # Save artifact here
  displayName: 'Download Previous Successful Artifact'
  condition: failed()  # Only run on failure

- script: |
    echo "Re-deploying the previous stable build..."
    xcopy "$(Build.ArtifactStagingDirectory)/rollback/*" "C:\YourDeploymentFolder" /E /Y  # Replace with your deployment folder
  displayName: 'Re-deploy Previous Artifact'
  condition: failed()  # Only run on failure

- script: |
    echo "Verifying files in deployment directory..."
    dir "C:\YourDeploymentFolder"  # Replace with your deployment folder path
  displayName: 'Verify Rollback Files'
  condition: failed()  # Only run on failure
