trigger: none  # Don't trigger on code changes

resources:
  pipelines:
    - pipeline: AutomatedTestingPipeline
      source: AutomatedTesting-.NET Desktop-CI
      trigger: true  # Trigger when the source pipeline completes

variables:
  ROBOT_REPORTS_DIR: 'robot_results'

pool:
  vmImage: 'windows-latest'

steps:

# 1. Use Python 3.11
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

# 2. Install Edge WebDriver manually
- powershell: |
    $edgeVersion = (Get-Item "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe").VersionInfo.ProductVersion
    Write-Host "Detected Edge version: $edgeVersion"
    $url = "https://msedgedriver.azureedge.net/$edgeVersion/edgedriver_win64.zip"
    Write-Host "Downloading WebDriver from $url"
    Invoke-WebRequest -Uri $url -OutFile "edgedriver.zip"
    Expand-Archive -Path "edgedriver.zip" -DestinationPath "$(Build.SourcesDirectory)\edgedriver" -Force
    $env:PATH += ";$(Build.SourcesDirectory)\edgedriver"
  displayName: 'Install Edge WebDriver manually'

# 3. Install Robot Framework and dependencies
- script: |
    python -m pip install --upgrade pip || exit 1
    pip install robotframework==6.1.1 || exit 1
    pip install robotframework-seleniumlibrary==6.1.2 || exit 1
  displayName: 'Install Robot Framework and dependencies'

# 4. Run Robot Framework tests
- script: |
    robot --variable BROWSER:edge ^
          --output "$(ROBOT_REPORTS_DIR)\output.xml" ^
          --log "$(ROBOT_REPORTS_DIR)\log.html" ^
          --report "$(ROBOT_REPORTS_DIR)\report.html" ^
          robot_test/
  displayName: 'Run Robot Framework Tests'
  continueOnError: true

# 5. Convert Robot Output to JUnit
- script: |
    rebot --xunit "$(ROBOT_REPORTS_DIR)\xunit.xml" "$(ROBOT_REPORTS_DIR)\output.xml"
  displayName: 'Convert Robot Output to JUnit'
  condition: always()

# 6. Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(ROBOT_REPORTS_DIR)\xunit.xml'
    testRunTitle: 'Robot Framework Test Results'
  condition: always()

# 7. Publish all Robot output files as artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(ROBOT_REPORTS_DIR)'
    artifactName: 'RobotResults'
  condition: always()

# 8. Get second latest successful build ID using REST API
- powershell: |
    $organization = "AutomatedTestingSSCGI"
    $project = "AutomatedTesting"
    $pipelineId = 1234  # <-- Replace with actual definition ID
    $pat = "$(System.AccessToken)"

    $uri = "https://dev.azure.com/$organization/$project/_apis/build/builds?definitions=$pipelineId&resultFilter=succeeded&queryOrder=finishTimeDescending&`$top=2&api-version=7.0"

    $response = Invoke-RestMethod -Uri $uri -Headers @{
      Authorization = "Bearer $pat"
    } -Method Get

    if ($response.count -ge 2) {
      $buildId = $response.value[1].id
      Write-Host "Found second latest successful build ID: $buildId"
      Write-Host "##vso[task.setvariable variable=PREVIOUS_SUCCESS_BUILD_ID]$buildId"
    } else {
      Write-Error "Not enough successful builds found."
      exit 1
    }
  env:
    System.AccessToken: $(System.AccessToken)
  displayName: 'Get Previous Successful Build ID'
  condition: failed()

# 9. Download the previous successful artifact
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'AutomatedTesting'
    pipeline: 'AutomatedTesting-.NET Desktop-CI'
    buildVersionToDownload: 'specific'
    specificBuildWithTriggering: false
    buildId: '$(PREVIOUS_SUCCESS_BUILD_ID)'
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)/rollback'
  displayName: 'Download Previous Successful Artifact'
  condition: failed()
  continueOnError: true

# 10. Inspect rollback artifact contents
- powershell: |
    Write-Host "Checking contents of rollback folder:"
    Get-ChildItem -Recurse "$(Build.ArtifactStagingDirectory)\rollback"
  displayName: 'Inspect Rollback Artifact'
  condition: failed()

# 11. Conditional redeploy with safe folder creation
- powershell: |
    $deployPath = "C:\YourDeploymentFolder"
    if (!(Test-Path $deployPath)) {
      New-Item -ItemType Directory -Force -Path $deployPath
    }

    if (Test-Path "$(Build.ArtifactStagingDirectory)\rollback") {
      Write-Host "Rollback artifact found. Re-deploying the previous stable build..."
      xcopy "$(Build.ArtifactStagingDirectory)\rollback\*" "$deployPath" /E /Y /I
    } else {
      Write-Warning "No rollback artifact found. Skipping deployment."
    }
  displayName: 'Conditional Redeploy of Previous Artifact'
  condition: failed()

# 12. Verify rollback folder contents
- powershell: |
    $path = "C:\YourDeploymentFolder"
    if (Test-Path $path) {
      Write-Host "Verifying files in deployment directory..."
      Get-ChildItem -Recurse $path
    } else {
      Write-Warning "Deployment folder does not exist."
      exit 1
    }
  displayName: 'Verify Rollback Files'
  condition: failed()
