trigger:
  branches:
    include:
      - main

jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    
    steps:
      - task: Checkout@1  # Corrected checkout task version
        displayName: 'Checkout code'
      
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
        displayName: 'Set up Python'
      
      - script: |
          python -m venv venv  # Create a virtual environment
          .\venv\Scripts\activate  # Activate the virtual environment on Windows
        displayName: 'Create and Activate Virtual Environment'

      - script: |
          .\venv\Scripts\activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies
        displayName: 'Install dependencies'

      - script: |
          .\venv\Scripts\activate  # Activate the virtual environment
          pip install robotframework  # Install Robot Framework
        displayName: 'Install Robot Framework'

      - script: |
          .\venv\Scripts\activate  # Activate the virtual environment
          robot --output output.xml path/to/your/tests  # Run the tests
        displayName: 'Run Robot Framework Tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/output.xml'  # Adjust this based on where your output.xml is saved
          mergeTestResults: true
        displayName: 'Publish Test Results'
