trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  ROBOT_REPORTS_DIR: 'robot_results'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
  displayName: 'Install Robot Framework and dependencies'


- script: |
    echo "Current directory:"
    cd
    echo "Listing contents of repo root:"
    dir
    echo "Listing contents of robot_tests (if exists):"
    dir robot_tests
  displayName: 'Debug: Show directory contents'
  
- script: |
    robot robot_tests/
  displayName: 'Run Robot Framework tests'
