trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest'

variables:
  ROBOT_REPORTS_DIR: 'robot_results'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.2'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
  displayName: 'Install Robot Framework and dependencies'


- script: |
    dir robot_tests   # This is for debugging, listing the directory contents
  displayName: 'List Robot Tests'

- script: |
    robot robot_tests/  # Run Robot Framework tests from the robot_tests directory
  displayName: 'Run Robot Framework tests'