trigger: none  # Don't trigger on code changes

resources:
  pipelines:
    - pipeline: AutomatedTestingPipeline  # Alias used if needed in jobs
      source: AutomatedTesting-.NET Desktop-CI
      trigger: true  # Trigger when the source pipeline completes

variables:
  ROBOT_REPORTS_DIR: 'robot_results'

pool:
  vmImage: 'windows-latest'

steps:

# 1. Use Python 3.11
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

# 2. Install Microsoft Edge WebDriver (latest version)
- script: |
    choco install microsoft-edge-driver -y
  displayName: 'Install Edge WebDriver'

# 3. Install Robot Framework and SeleniumLibrary with fail-fast
- script: |
    python -m pip install --upgrade pip || exit 1
    pip install robotframework==6.1.1 || exit 1
    pip install robotframework-seleniumlibrary==6.1.2 || exit 1
  displayName: 'Install Robot Framework and dependencies with fail-fast'

# 4. Debug: Confirm installations
- script: |
    where python
    where pip
    where robot
    pip list
  displayName: 'Debug: Confirm installations'

# 5. Debug: Show project structure
- script: |
    echo "Current directory:"
    cd
    echo "Repo root contents:"
    dir
    echo "robot_test folder contents:"
    dir robot_test
  displayName: 'Debug: Show project structure'

# 6. Ensure report directory exists
- script: |
    if not exist "$(ROBOT_REPORTS_DIR)" mkdir "$(ROBOT_REPORTS_DIR)"
  displayName: 'Ensure robot_results directory exists'

# 7. Run Robot Framework Test
- script: |
    robot --variable BROWSER:
