trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest'  # Or your preferred VM image


variables:
  ROBOT_REPORTS_DIR: 'robot_results'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.2'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
    # Add more libraries if needed
  displayName: 'Install Robot Framework and dependencies'

- script: |
    mkdir -p $(ROBOT_REPORTS_DIR)
    robot --outputdir $(ROBOT_REPORTS_DIR) tests/
  displayName: 'Run Robot Framework Tests'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(ROBOT_REPORTS_DIR)/output.xml'
    testRunTitle: 'Robot Framework Test Results'
    
